/**
 * formFields.js
 *
 * Reusable field definitions. Components like InputField pick up
 * label / placeholder / type / validation / icon from these entries —
 * never hardcode them in pages.
 *
 * Required fields show a red asterisk attached to the label with NO space
 * ("Name*", not "Name *").
 *
 * Placeholders follow the convention "Enter <Label>" unless a stricter
 * format is appropriate (e.g. DD/MM/YYYY for date).
 */

import {
  Mail,
  Phone,
  User as UserIcon,
  Lock,
  KeyRound,
  Globe,
  MapPin,
  Hash,
  CalendarDays,
  Clock,
  AlignLeft,
  FileText,
  Tag,
  Type,
  CreditCard,
  Ticket,
  Gift,
} from 'lucide-react';

import { LABELS } from './labels.js';
import { RULES } from './validationRules.js';

const enterLabel = (label) => `Enter ${label}`;

export const FORM_FIELDS = {
  fullName: {
    name: 'fullName',
    label: LABELS.fullName,
    placeholder: enterLabel(LABELS.fullName),
    type: 'text',
    required: true,
    minLength: RULES.fullName.minLength,
    maxLength: RULES.fullName.maxLength,
    validationRule: 'fullName',
    showAsterisk: true,
    icon: UserIcon,
    allowOnly: 'lettersSpaces',
    trimOnBlur: true,
    defaultValue: '',
  },
  firstName: {
    name: 'firstName',
    label: LABELS.firstName,
    placeholder: enterLabel(LABELS.firstName),
    type: 'text',
    required: true,
    minLength: 2,
    maxLength: 30,
    validationRule: 'firstName',
    showAsterisk: true,
    icon: UserIcon,
    allowOnly: 'lettersSpaces',
    trimOnBlur: true,
    defaultValue: '',
  },
  lastName: {
    name: 'lastName',
    label: LABELS.lastName,
    placeholder: enterLabel(LABELS.lastName),
    type: 'text',
    required: true,
    minLength: 1,
    maxLength: 30,
    validationRule: 'lastName',
    showAsterisk: true,
    icon: UserIcon,
    allowOnly: 'lettersSpaces',
    trimOnBlur: true,
    defaultValue: '',
  },
  emailId: {
    name: 'emailId',
    label: LABELS.emailId,
    placeholder: enterLabel(LABELS.emailId),
    type: 'email',
    required: true,
    minLength: RULES.emailId.minLength,
    maxLength: RULES.emailId.maxLength,
    validationRule: 'emailId',
    showAsterisk: true,
    icon: Mail,
    inputMode: 'email',
    trimOnBlur: true,
    defaultValue: '',
  },
  contactNumber: {
    name: 'contactNumber',
    label: LABELS.contactNumber,
    placeholder: enterLabel(LABELS.contactNumber),
    type: 'tel',
    required: true,
    minLength: RULES.contactNumber.minLength,
    maxLength: 10,
    validationRule: 'contactNumber',
    showAsterisk: true,
    icon: Phone,
    allowOnly: 'digits',
    inputMode: 'numeric',
    defaultValue: '',
  },
  password: {
    name: 'password',
    label: LABELS.password,
    placeholder: enterLabel(LABELS.password),
    type: 'password',
    required: true,
    minLength: RULES.password.minLength,
    maxLength: RULES.password.maxLength,
    validationRule: 'password',
    showAsterisk: true,
    icon: Lock,
    defaultValue: '',
  },
  confirmPassword: {
    name: 'confirmPassword',
    label: LABELS.confirmPassword,
    placeholder: enterLabel(LABELS.confirmPassword),
    type: 'password',
    required: true,
    validationRule: 'confirmPassword',
    showAsterisk: true,
    icon: Lock,
    defaultValue: '',
  },
  currentPassword: {
    name: 'currentPassword',
    label: LABELS.currentPassword,
    placeholder: enterLabel(LABELS.currentPassword),
    type: 'password',
    required: true,
    validationRule: 'currentPassword',
    showAsterisk: true,
    icon: KeyRound,
    defaultValue: '',
  },
  newPassword: {
    name: 'newPassword',
    label: LABELS.newPassword,
    placeholder: enterLabel(LABELS.newPassword),
    type: 'password',
    required: true,
    validationRule: 'newPassword',
    showAsterisk: true,
    icon: KeyRound,
    defaultValue: '',
  },
  country: {
    name: 'country',
    label: LABELS.country,
    placeholder: `Select ${LABELS.country}`,
    type: 'select',
    required: true,
    validationRule: 'country',
    showAsterisk: true,
    icon: Globe,
    options: [],
    defaultValue: '',
  },
  state: {
    name: 'state',
    label: LABELS.state,
    placeholder: `Select ${LABELS.state}`,
    type: 'select',
    required: true,
    validationRule: 'state',
    showAsterisk: true,
    icon: MapPin,
    options: [],
    defaultValue: '',
  },
  city: {
    name: 'city',
    label: LABELS.city,
    placeholder: `Select ${LABELS.city}`,
    type: 'select',
    required: true,
    validationRule: 'city',
    showAsterisk: true,
    icon: MapPin,
    options: [],
    defaultValue: '',
  },
  postalCode: {
    name: 'postalCode',
    label: LABELS.postalCode,
    placeholder: enterLabel(LABELS.postalCode),
    type: 'text',
    required: true,
    minLength: RULES.postalCode.minLength,
    maxLength: RULES.postalCode.maxLength,
    validationRule: 'postalCode',
    showAsterisk: true,
    icon: Hash,
    allowOnly: 'digits',
    inputMode: 'numeric',
    defaultValue: '',
  },
  date: {
    name: 'date',
    label: LABELS.date,
    placeholder: 'DD/MM/YYYY',
    type: 'date',
    required: true,
    validationRule: 'date',
    showAsterisk: true,
    icon: CalendarDays,
    defaultValue: '',
  },
  time: {
    name: 'time',
    label: LABELS.time,
    placeholder: 'hh:mm AM/PM',
    type: 'time',
    required: false,
    showAsterisk: false,
    icon: Clock,
    defaultValue: '',
  },
  message: {
    name: 'message',
    label: LABELS.message,
    placeholder: enterLabel(LABELS.message),
    type: 'textarea',
    required: false,
    maxLength: RULES.message.maxLength,
    validationRule: 'message',
    showAsterisk: false,
    icon: AlignLeft,
    rows: 4,
    maxRows: RULES.message.maxRows,
    defaultValue: '',
  },
  description: {
    name: 'description',
    label: LABELS.description,
    placeholder: enterLabel(LABELS.description),
    type: 'textarea',
    required: false,
    maxLength: RULES.description.maxLength,
    validationRule: 'description',
    showAsterisk: false,
    icon: FileText,
    rows: 5,
    maxRows: RULES.description.maxRows,
    defaultValue: '',
  },
  campaignName: {
    name: 'campaignName',
    label: LABELS.campaignName,
    placeholder: enterLabel(LABELS.campaignName),
    type: 'text',
    required: true,
    minLength: RULES.campaignName.minLength,
    maxLength: RULES.campaignName.maxLength,
    validationRule: 'campaignName',
    showAsterisk: true,
    icon: Tag,
    defaultValue: '',
  },
  templateName: {
    name: 'templateName',
    label: LABELS.templateName,
    placeholder: enterLabel(LABELS.templateName),
    type: 'text',
    required: true,
    minLength: RULES.templateName.minLength,
    maxLength: RULES.templateName.maxLength,
    validationRule: 'templateName',
    showAsterisk: true,
    icon: Tag,
    defaultValue: '',
  },
  subjectLine: {
    name: 'subjectLine',
    label: LABELS.subjectLine,
    placeholder: enterLabel(LABELS.subjectLine),
    type: 'text',
    required: true,
    minLength: RULES.subjectLine.minLength,
    maxLength: RULES.subjectLine.maxLength,
    validationRule: 'subjectLine',
    showAsterisk: true,
    icon: Type,
    defaultValue: '',
  },
  senderName: {
    name: 'senderName',
    label: LABELS.senderName,
    placeholder: enterLabel(LABELS.senderName),
    type: 'text',
    required: true,
    minLength: RULES.senderName.minLength,
    maxLength: RULES.senderName.maxLength,
    validationRule: 'senderName',
    showAsterisk: true,
    icon: UserIcon,
    allowOnly: 'lettersSpaces',
    trimOnBlur: true,
    defaultValue: '',
  },
  senderEmailId: {
    name: 'senderEmailId',
    label: LABELS.senderEmailId,
    placeholder: enterLabel(LABELS.senderEmailId),
    type: 'email',
    required: true,
    validationRule: 'senderEmailId',
    showAsterisk: true,
    icon: Mail,
    defaultValue: '',
  },
  couponCode: {
    name: 'couponCode',
    label: LABELS.couponCode,
    placeholder: enterLabel(LABELS.couponCode),
    type: 'text',
    required: true,
    minLength: RULES.couponCode.minLength,
    maxLength: RULES.couponCode.maxLength,
    validationRule: 'couponCode',
    showAsterisk: true,
    icon: Ticket,
    allowOnly: 'alphanumeric',
    trimOnBlur: true,
    defaultValue: '',
  },
  referralCode: {
    name: 'referralCode',
    label: LABELS.referralCode,
    placeholder: enterLabel(LABELS.referralCode),
    type: 'text',
    required: true,
    minLength: RULES.referralCode.minLength,
    maxLength: RULES.referralCode.maxLength,
    validationRule: 'referralCode',
    showAsterisk: true,
    icon: Gift,
    allowOnly: 'alphanumeric',
    trimOnBlur: true,
    defaultValue: '',
  },
  planName: {
    name: 'planName',
    label: LABELS.planName,
    placeholder: enterLabel(LABELS.planName),
    type: 'text',
    required: true,
    minLength: RULES.planName.minLength,
    maxLength: RULES.planName.maxLength,
    validationRule: 'planName',
    showAsterisk: true,
    icon: CreditCard,
    defaultValue: '',
  },
  price: {
    name: 'price',
    label: LABELS.price,
    placeholder: enterLabel(LABELS.price),
    type: 'text',
    required: true,
    validationRule: 'price',
    showAsterisk: true,
    icon: CreditCard,
    allowOnly: 'decimal',
    inputMode: 'decimal',
    defaultValue: '',
  },
  terms: {
    name: 'terms',
    label: 'Terms of Service and Privacy Policy',
    type: 'checkbox',
    required: true,
    validationRule: 'terms',
    showAsterisk: true,
    defaultValue: false,
  },
};

export function getField(name) {
  return FORM_FIELDS[name] || null;
}

export default FORM_FIELDS;
